//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ElijaModel", "UserDevice", "Device", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Device), "User", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.User))]

#endregion

namespace Freakybite.ElijaWebServices.DataAccess.Model
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ElijaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ElijaEntities usando la cadena de conexión encontrada en la sección 'ElijaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ElijaEntities() : base("name=ElijaEntities", "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ElijaEntities.
        /// </summary>
        public ElijaEntities(string connectionString) : base(connectionString, "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ElijaEntities.
        /// </summary>
        public ElijaEntities(EntityConnection connection) : base(connection, "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Device> Device
        {
            get
            {
                if ((_Device == null))
                {
                    _Device = base.CreateObjectSet<Device>("Device");
                }
                return _Device;
            }
        }
        private ObjectSet<Device> _Device;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Device. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDevice(Device device)
        {
            base.AddObject("Device", device);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet User. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="Device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Device : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Device.
        /// </summary>
        /// <param name="deviceId">Valor inicial de la propiedad DeviceId.</param>
        /// <param name="iMEI">Valor inicial de la propiedad IMEI.</param>
        /// <param name="brand">Valor inicial de la propiedad Brand.</param>
        /// <param name="device1">Valor inicial de la propiedad Device1.</param>
        /// <param name="display">Valor inicial de la propiedad Display.</param>
        /// <param name="manufacturer">Valor inicial de la propiedad Manufacturer.</param>
        /// <param name="model">Valor inicial de la propiedad Model.</param>
        /// <param name="product">Valor inicial de la propiedad Product.</param>
        /// <param name="operator">Valor inicial de la propiedad Operator.</param>
        /// <param name="androidId">Valor inicial de la propiedad AndroidId.</param>
        /// <param name="osVersion">Valor inicial de la propiedad OsVersion.</param>
        /// <param name="codeVersion">Valor inicial de la propiedad CodeVersion.</param>
        /// <param name="releaseVersion">Valor inicial de la propiedad ReleaseVersion.</param>
        /// <param name="isPhone">Valor inicial de la propiedad IsPhone.</param>
        /// <param name="registrationDate">Valor inicial de la propiedad RegistrationDate.</param>
        public static Device CreateDevice(global::System.Int64 deviceId, global::System.String iMEI, global::System.String brand, global::System.String device1, global::System.String display, global::System.String manufacturer, global::System.String model, global::System.String product, global::System.String @operator, global::System.String androidId, global::System.String osVersion, global::System.String codeVersion, global::System.String releaseVersion, global::System.Boolean isPhone, global::System.DateTime registrationDate)
        {
            Device device = new Device();
            device.DeviceId = deviceId;
            device.IMEI = iMEI;
            device.Brand = brand;
            device.Device1 = device1;
            device.Display = display;
            device.Manufacturer = manufacturer;
            device.Model = model;
            device.Product = product;
            device.Operator = @operator;
            device.AndroidId = androidId;
            device.OsVersion = osVersion;
            device.CodeVersion = codeVersion;
            device.ReleaseVersion = releaseVersion;
            device.IsPhone = isPhone;
            device.RegistrationDate = registrationDate;
            return device;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DeviceId
        {
            get
            {
                return _DeviceId;
            }
            set
            {
                if (_DeviceId != value)
                {
                    OnDeviceIdChanging(value);
                    ReportPropertyChanging("DeviceId");
                    _DeviceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceId");
                    OnDeviceIdChanged();
                }
            }
        }
        private global::System.Int64 _DeviceId;
        partial void OnDeviceIdChanging(global::System.Int64 value);
        partial void OnDeviceIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private global::System.String _IMEI;
        partial void OnIMEIChanging(global::System.String value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Device1
        {
            get
            {
                return _Device1;
            }
            set
            {
                OnDevice1Changing(value);
                ReportPropertyChanging("Device1");
                _Device1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Device1");
                OnDevice1Changed();
            }
        }
        private global::System.String _Device1;
        partial void OnDevice1Changing(global::System.String value);
        partial void OnDevice1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Display
        {
            get
            {
                return _Display;
            }
            set
            {
                OnDisplayChanging(value);
                ReportPropertyChanging("Display");
                _Display = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Display");
                OnDisplayChanged();
            }
        }
        private global::System.String _Display;
        partial void OnDisplayChanging(global::System.String value);
        partial void OnDisplayChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Operator
        {
            get
            {
                return _Operator;
            }
            set
            {
                OnOperatorChanging(value);
                ReportPropertyChanging("Operator");
                _Operator = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Operator");
                OnOperatorChanged();
            }
        }
        private global::System.String _Operator;
        partial void OnOperatorChanging(global::System.String value);
        partial void OnOperatorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AndroidId
        {
            get
            {
                return _AndroidId;
            }
            set
            {
                OnAndroidIdChanging(value);
                ReportPropertyChanging("AndroidId");
                _AndroidId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AndroidId");
                OnAndroidIdChanged();
            }
        }
        private global::System.String _AndroidId;
        partial void OnAndroidIdChanging(global::System.String value);
        partial void OnAndroidIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OsVersion
        {
            get
            {
                return _OsVersion;
            }
            set
            {
                OnOsVersionChanging(value);
                ReportPropertyChanging("OsVersion");
                _OsVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OsVersion");
                OnOsVersionChanged();
            }
        }
        private global::System.String _OsVersion;
        partial void OnOsVersionChanging(global::System.String value);
        partial void OnOsVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeVersion
        {
            get
            {
                return _CodeVersion;
            }
            set
            {
                OnCodeVersionChanging(value);
                ReportPropertyChanging("CodeVersion");
                _CodeVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeVersion");
                OnCodeVersionChanged();
            }
        }
        private global::System.String _CodeVersion;
        partial void OnCodeVersionChanging(global::System.String value);
        partial void OnCodeVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReleaseVersion
        {
            get
            {
                return _ReleaseVersion;
            }
            set
            {
                OnReleaseVersionChanging(value);
                ReportPropertyChanging("ReleaseVersion");
                _ReleaseVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReleaseVersion");
                OnReleaseVersionChanged();
            }
        }
        private global::System.String _ReleaseVersion;
        partial void OnReleaseVersionChanging(global::System.String value);
        partial void OnReleaseVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPhone
        {
            get
            {
                return _IsPhone;
            }
            set
            {
                OnIsPhoneChanging(value);
                ReportPropertyChanging("IsPhone");
                _IsPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPhone");
                OnIsPhoneChanged();
            }
        }
        private global::System.Boolean _IsPhone;
        partial void OnIsPhoneChanging(global::System.Boolean value);
        partial void OnIsPhoneChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private global::System.DateTime _RegistrationDate;
        partial void OnRegistrationDateChanging(global::System.DateTime value);
        partial void OnRegistrationDateChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "UserDevice", "User")]
        public EntityCollection<User> User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("ElijaModel.UserDevice", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("ElijaModel.UserDevice", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto User.
        /// </summary>
        /// <param name="facebookId">Valor inicial de la propiedad FacebookId.</param>
        public static User CreateUser(global::System.Int64 facebookId)
        {
            User user = new User();
            user.FacebookId = facebookId;
            return user;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FacebookId
        {
            get
            {
                return _FacebookId;
            }
            set
            {
                if (_FacebookId != value)
                {
                    OnFacebookIdChanging(value);
                    ReportPropertyChanging("FacebookId");
                    _FacebookId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FacebookId");
                    OnFacebookIdChanged();
                }
            }
        }
        private global::System.Int64 _FacebookId;
        partial void OnFacebookIdChanging(global::System.Int64 value);
        partial void OnFacebookIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookLink
        {
            get
            {
                return _FacebookLink;
            }
            set
            {
                OnFacebookLinkChanging(value);
                ReportPropertyChanging("FacebookLink");
                _FacebookLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookLink");
                OnFacebookLinkChanged();
            }
        }
        private global::System.String _FacebookLink;
        partial void OnFacebookLinkChanging(global::System.String value);
        partial void OnFacebookLinkChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneHome
        {
            get
            {
                return _TelephoneHome;
            }
            set
            {
                OnTelephoneHomeChanging(value);
                ReportPropertyChanging("TelephoneHome");
                _TelephoneHome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneHome");
                OnTelephoneHomeChanged();
            }
        }
        private global::System.String _TelephoneHome;
        partial void OnTelephoneHomeChanging(global::System.String value);
        partial void OnTelephoneHomeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneOffice
        {
            get
            {
                return _TelephoneOffice;
            }
            set
            {
                OnTelephoneOfficeChanging(value);
                ReportPropertyChanging("TelephoneOffice");
                _TelephoneOffice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneOffice");
                OnTelephoneOfficeChanged();
            }
        }
        private global::System.String _TelephoneOffice;
        partial void OnTelephoneOfficeChanging(global::System.String value);
        partial void OnTelephoneOfficeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneMobile
        {
            get
            {
                return _TelephoneMobile;
            }
            set
            {
                OnTelephoneMobileChanging(value);
                ReportPropertyChanging("TelephoneMobile");
                _TelephoneMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneMobile");
                OnTelephoneMobileChanged();
            }
        }
        private global::System.String _TelephoneMobile;
        partial void OnTelephoneMobileChanging(global::System.String value);
        partial void OnTelephoneMobileChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDate;
        partial void OnRegistrationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDateChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "UserDevice", "Device")]
        public EntityCollection<Device> Device
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Device>("ElijaModel.UserDevice", "Device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Device>("ElijaModel.UserDevice", "Device", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
