//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ElijaModel", "FK__Article__Section__5EBF139D", "Section", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Section), "Article", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Article), true)]
[assembly: EdmRelationshipAttribute("ElijaModel", "FK__ArticleAs__Artic__693CA210", "Article", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Article), "ArticleAsset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.ArticleAsset), true)]
[assembly: EdmRelationshipAttribute("ElijaModel", "FK__ArticleAs__Image__6A30C649", "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Image), "ArticleAsset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.ArticleAsset), true)]
[assembly: EdmRelationshipAttribute("ElijaModel", "FK__ArticleAs__Video__6B24EA82", "Video", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Video), "ArticleAsset", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.ArticleAsset), true)]
[assembly: EdmRelationshipAttribute("ElijaModel", "FK__UserDevic__Devic__4AB81AF0", "Device", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Freakybite.ElijaWebServices.DataAccess.Model.Device), "UserDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.UserDevice), true)]
[assembly: EdmRelationshipAttribute("ElijaModel", "FK__UserDevic__UserI__49C3F6B7", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Freakybite.ElijaWebServices.DataAccess.Model.User), "UserDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Freakybite.ElijaWebServices.DataAccess.Model.UserDevice), true)]

#endregion

namespace Freakybite.ElijaWebServices.DataAccess.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ElijaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ElijaEntities object using the connection string found in the 'ElijaEntities' section of the application configuration file.
        /// </summary>
        public ElijaEntities() : base("name=ElijaEntities", "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ElijaEntities object.
        /// </summary>
        public ElijaEntities(string connectionString) : base(connectionString, "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ElijaEntities object.
        /// </summary>
        public ElijaEntities(EntityConnection connection) : base(connection, "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article> Article
        {
            get
            {
                if ((_Article == null))
                {
                    _Article = base.CreateObjectSet<Article>("Article");
                }
                return _Article;
            }
        }
        private ObjectSet<Article> _Article;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArticleAsset> ArticleAsset
        {
            get
            {
                if ((_ArticleAsset == null))
                {
                    _ArticleAsset = base.CreateObjectSet<ArticleAsset>("ArticleAsset");
                }
                return _ArticleAsset;
            }
        }
        private ObjectSet<ArticleAsset> _ArticleAsset;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Device> Device
        {
            get
            {
                if ((_Device == null))
                {
                    _Device = base.CreateObjectSet<Device>("Device");
                }
                return _Device;
            }
        }
        private ObjectSet<Device> _Device;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Image
        {
            get
            {
                if ((_Image == null))
                {
                    _Image = base.CreateObjectSet<Image>("Image");
                }
                return _Image;
            }
        }
        private ObjectSet<Image> _Image;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Section> Section
        {
            get
            {
                if ((_Section == null))
                {
                    _Section = base.CreateObjectSet<Section>("Section");
                }
                return _Section;
            }
        }
        private ObjectSet<Section> _Section;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserDevice> UserDevice
        {
            get
            {
                if ((_UserDevice == null))
                {
                    _UserDevice = base.CreateObjectSet<UserDevice>("UserDevice");
                }
                return _UserDevice;
            }
        }
        private ObjectSet<UserDevice> _UserDevice;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Video> Video
        {
            get
            {
                if ((_Video == null))
                {
                    _Video = base.CreateObjectSet<Video>("Video");
                }
                return _Video;
            }
        }
        private ObjectSet<Video> _Video;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Article EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticle(Article article)
        {
            base.AddObject("Article", article);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArticleAsset EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticleAsset(ArticleAsset articleAsset)
        {
            base.AddObject("ArticleAsset", articleAsset);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Device EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDevice(Device device)
        {
            base.AddObject("Device", device);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Image EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImage(Image image)
        {
            base.AddObject("Image", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Section EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSection(Section section)
        {
            base.AddObject("Section", section);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserDevice EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserDevice(UserDevice userDevice)
        {
            base.AddObject("UserDevice", userDevice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Video EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideo(Video video)
        {
            base.AddObject("Video", video);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="Article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="articleId">Initial value of the ArticleId property.</param>
        /// <param name="sectionId">Initial value of the SectionId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        /// <param name="updatedAt">Initial value of the UpdatedAt property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="thumbnail">Initial value of the Thumbnail property.</param>
        public static Article CreateArticle(global::System.Int32 articleId, global::System.Int32 sectionId, global::System.String title, global::System.String description, global::System.DateTime createdAt, global::System.DateTime updatedAt, global::System.Boolean isActive, global::System.String thumbnail)
        {
            Article article = new Article();
            article.ArticleId = articleId;
            article.SectionId = sectionId;
            article.Title = title;
            article.Description = description;
            article.CreatedAt = createdAt;
            article.UpdatedAt = updatedAt;
            article.IsActive = isActive;
            article.Thumbnail = thumbnail;
            return article;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                if (_ArticleId != value)
                {
                    OnArticleIdChanging(value);
                    ReportPropertyChanging("ArticleId");
                    _ArticleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticleId");
                    OnArticleIdChanged();
                }
            }
        }
        private global::System.Int32 _ArticleId;
        partial void OnArticleIdChanging(global::System.Int32 value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionId
        {
            get
            {
                return _SectionId;
            }
            set
            {
                OnSectionIdChanging(value);
                ReportPropertyChanging("SectionId");
                _SectionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SectionId");
                OnSectionIdChanged();
            }
        }
        private global::System.Int32 _SectionId;
        partial void OnSectionIdChanging(global::System.Int32 value);
        partial void OnSectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedAt
        {
            get
            {
                return _UpdatedAt;
            }
            set
            {
                OnUpdatedAtChanging(value);
                ReportPropertyChanging("UpdatedAt");
                _UpdatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedAt");
                OnUpdatedAtChanged();
            }
        }
        private global::System.DateTime _UpdatedAt;
        partial void OnUpdatedAtChanging(global::System.DateTime value);
        partial void OnUpdatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Thumbnail
        {
            get
            {
                return _Thumbnail;
            }
            set
            {
                OnThumbnailChanging(value);
                ReportPropertyChanging("Thumbnail");
                _Thumbnail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Thumbnail");
                OnThumbnailChanged();
            }
        }
        private global::System.String _Thumbnail;
        partial void OnThumbnailChanging(global::System.String value);
        partial void OnThumbnailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__Article__Section__5EBF139D", "Section")]
        public Section Section
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("ElijaModel.FK__Article__Section__5EBF139D", "Section").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("ElijaModel.FK__Article__Section__5EBF139D", "Section").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Section> SectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Section>("ElijaModel.FK__Article__Section__5EBF139D", "Section");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Section>("ElijaModel.FK__Article__Section__5EBF139D", "Section", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__ArticleAs__Artic__693CA210", "ArticleAsset")]
        public EntityCollection<ArticleAsset> ArticleAsset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ArticleAsset>("ElijaModel.FK__ArticleAs__Artic__693CA210", "ArticleAsset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ArticleAsset>("ElijaModel.FK__ArticleAs__Artic__693CA210", "ArticleAsset", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="ArticleAsset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArticleAsset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArticleAsset object.
        /// </summary>
        /// <param name="articleAssetId">Initial value of the ArticleAssetId property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static ArticleAsset CreateArticleAsset(global::System.Int32 articleAssetId, global::System.DateTime createdAt)
        {
            ArticleAsset articleAsset = new ArticleAsset();
            articleAsset.ArticleAssetId = articleAssetId;
            articleAsset.CreatedAt = createdAt;
            return articleAsset;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ArticleAssetId
        {
            get
            {
                return _ArticleAssetId;
            }
            set
            {
                if (_ArticleAssetId != value)
                {
                    OnArticleAssetIdChanging(value);
                    ReportPropertyChanging("ArticleAssetId");
                    _ArticleAssetId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ArticleAssetId");
                    OnArticleAssetIdChanged();
                }
            }
        }
        private global::System.Int32 _ArticleAssetId;
        partial void OnArticleAssetIdChanging(global::System.Int32 value);
        partial void OnArticleAssetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ArticleId
        {
            get
            {
                return _ArticleId;
            }
            set
            {
                OnArticleIdChanging(value);
                ReportPropertyChanging("ArticleId");
                _ArticleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArticleId");
                OnArticleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ArticleId;
        partial void OnArticleIdChanging(Nullable<global::System.Int32> value);
        partial void OnArticleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                OnImageIdChanging(value);
                ReportPropertyChanging("ImageId");
                _ImageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageId");
                OnImageIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ImageId;
        partial void OnImageIdChanging(Nullable<global::System.Int32> value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VideoId
        {
            get
            {
                return _VideoId;
            }
            set
            {
                OnVideoIdChanging(value);
                ReportPropertyChanging("VideoId");
                _VideoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VideoId");
                OnVideoIdChanged();
            }
        }
        private Nullable<global::System.Int32> _VideoId;
        partial void OnVideoIdChanging(Nullable<global::System.Int32> value);
        partial void OnVideoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__ArticleAs__Artic__693CA210", "Article")]
        public Article Article
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("ElijaModel.FK__ArticleAs__Artic__693CA210", "Article").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("ElijaModel.FK__ArticleAs__Artic__693CA210", "Article").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Article> ArticleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("ElijaModel.FK__ArticleAs__Artic__693CA210", "Article");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Article>("ElijaModel.FK__ArticleAs__Artic__693CA210", "Article", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__ArticleAs__Image__6A30C649", "Image")]
        public Image Image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Image>("ElijaModel.FK__ArticleAs__Image__6A30C649", "Image").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Image>("ElijaModel.FK__ArticleAs__Image__6A30C649", "Image").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Image> ImageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Image>("ElijaModel.FK__ArticleAs__Image__6A30C649", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Image>("ElijaModel.FK__ArticleAs__Image__6A30C649", "Image", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__ArticleAs__Video__6B24EA82", "Video")]
        public Video Video
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Video>("ElijaModel.FK__ArticleAs__Video__6B24EA82", "Video").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Video>("ElijaModel.FK__ArticleAs__Video__6B24EA82", "Video").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Video> VideoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Video>("ElijaModel.FK__ArticleAs__Video__6B24EA82", "Video");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Video>("ElijaModel.FK__ArticleAs__Video__6B24EA82", "Video", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="Device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Device : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="deviceId">Initial value of the DeviceId property.</param>
        /// <param name="brand">Initial value of the Brand property.</param>
        /// <param name="device1">Initial value of the Device1 property.</param>
        /// <param name="display">Initial value of the Display property.</param>
        /// <param name="manufacturer">Initial value of the Manufacturer property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="product">Initial value of the Product property.</param>
        /// <param name="androidId">Initial value of the AndroidId property.</param>
        /// <param name="osVersion">Initial value of the OsVersion property.</param>
        /// <param name="codeVersion">Initial value of the CodeVersion property.</param>
        /// <param name="releaseVersion">Initial value of the ReleaseVersion property.</param>
        /// <param name="isPhone">Initial value of the IsPhone property.</param>
        /// <param name="registrationDate">Initial value of the RegistrationDate property.</param>
        public static Device CreateDevice(global::System.Int64 deviceId, global::System.String brand, global::System.String device1, global::System.Int32 display, global::System.String manufacturer, global::System.String model, global::System.String product, global::System.String androidId, global::System.String osVersion, global::System.String codeVersion, global::System.String releaseVersion, global::System.Boolean isPhone, global::System.DateTime registrationDate)
        {
            Device device = new Device();
            device.DeviceId = deviceId;
            device.Brand = brand;
            device.Device1 = device1;
            device.Display = display;
            device.Manufacturer = manufacturer;
            device.Model = model;
            device.Product = product;
            device.AndroidId = androidId;
            device.OsVersion = osVersion;
            device.CodeVersion = codeVersion;
            device.ReleaseVersion = releaseVersion;
            device.IsPhone = isPhone;
            device.RegistrationDate = registrationDate;
            return device;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DeviceId
        {
            get
            {
                return _DeviceId;
            }
            set
            {
                if (_DeviceId != value)
                {
                    OnDeviceIdChanging(value);
                    ReportPropertyChanging("DeviceId");
                    _DeviceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceId");
                    OnDeviceIdChanged();
                }
            }
        }
        private global::System.Int64 _DeviceId;
        partial void OnDeviceIdChanging(global::System.Int64 value);
        partial void OnDeviceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private Nullable<global::System.Int64> _IMEI;
        partial void OnIMEIChanging(Nullable<global::System.Int64> value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Device1
        {
            get
            {
                return _Device1;
            }
            set
            {
                OnDevice1Changing(value);
                ReportPropertyChanging("Device1");
                _Device1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Device1");
                OnDevice1Changed();
            }
        }
        private global::System.String _Device1;
        partial void OnDevice1Changing(global::System.String value);
        partial void OnDevice1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Display
        {
            get
            {
                return _Display;
            }
            set
            {
                OnDisplayChanging(value);
                ReportPropertyChanging("Display");
                _Display = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Display");
                OnDisplayChanged();
            }
        }
        private global::System.Int32 _Display;
        partial void OnDisplayChanging(global::System.Int32 value);
        partial void OnDisplayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Operator
        {
            get
            {
                return _Operator;
            }
            set
            {
                OnOperatorChanging(value);
                ReportPropertyChanging("Operator");
                _Operator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Operator");
                OnOperatorChanged();
            }
        }
        private global::System.String _Operator;
        partial void OnOperatorChanging(global::System.String value);
        partial void OnOperatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AndroidId
        {
            get
            {
                return _AndroidId;
            }
            set
            {
                OnAndroidIdChanging(value);
                ReportPropertyChanging("AndroidId");
                _AndroidId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AndroidId");
                OnAndroidIdChanged();
            }
        }
        private global::System.String _AndroidId;
        partial void OnAndroidIdChanging(global::System.String value);
        partial void OnAndroidIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OsVersion
        {
            get
            {
                return _OsVersion;
            }
            set
            {
                OnOsVersionChanging(value);
                ReportPropertyChanging("OsVersion");
                _OsVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OsVersion");
                OnOsVersionChanged();
            }
        }
        private global::System.String _OsVersion;
        partial void OnOsVersionChanging(global::System.String value);
        partial void OnOsVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeVersion
        {
            get
            {
                return _CodeVersion;
            }
            set
            {
                OnCodeVersionChanging(value);
                ReportPropertyChanging("CodeVersion");
                _CodeVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeVersion");
                OnCodeVersionChanged();
            }
        }
        private global::System.String _CodeVersion;
        partial void OnCodeVersionChanging(global::System.String value);
        partial void OnCodeVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReleaseVersion
        {
            get
            {
                return _ReleaseVersion;
            }
            set
            {
                OnReleaseVersionChanging(value);
                ReportPropertyChanging("ReleaseVersion");
                _ReleaseVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReleaseVersion");
                OnReleaseVersionChanged();
            }
        }
        private global::System.String _ReleaseVersion;
        partial void OnReleaseVersionChanging(global::System.String value);
        partial void OnReleaseVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPhone
        {
            get
            {
                return _IsPhone;
            }
            set
            {
                OnIsPhoneChanging(value);
                ReportPropertyChanging("IsPhone");
                _IsPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPhone");
                OnIsPhoneChanged();
            }
        }
        private global::System.Boolean _IsPhone;
        partial void OnIsPhoneChanging(global::System.Boolean value);
        partial void OnIsPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private global::System.DateTime _RegistrationDate;
        partial void OnRegistrationDateChanging(global::System.DateTime value);
        partial void OnRegistrationDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__UserDevic__Devic__4AB81AF0", "UserDevice")]
        public EntityCollection<UserDevice> UserDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserDevice>("ElijaModel.FK__UserDevic__Devic__4AB81AF0", "UserDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserDevice>("ElijaModel.FK__UserDevic__Devic__4AB81AF0", "UserDevice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="imageId">Initial value of the ImageId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="size">Initial value of the Size property.</param>
        public static Image CreateImage(global::System.Int32 imageId, global::System.String url, global::System.Int32 width, global::System.Int32 height, global::System.Int32 size)
        {
            Image image = new Image();
            image.ImageId = imageId;
            image.Url = url;
            image.Width = width;
            image.Height = height;
            image.Size = size;
            return image;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                if (_ImageId != value)
                {
                    OnImageIdChanging(value);
                    ReportPropertyChanging("ImageId");
                    _ImageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageId");
                    OnImageIdChanged();
                }
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.Int32 _Size;
        partial void OnSizeChanging(global::System.Int32 value);
        partial void OnSizeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__ArticleAs__Image__6A30C649", "ArticleAsset")]
        public EntityCollection<ArticleAsset> ArticleAsset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ArticleAsset>("ElijaModel.FK__ArticleAs__Image__6A30C649", "ArticleAsset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ArticleAsset>("ElijaModel.FK__ArticleAs__Image__6A30C649", "ArticleAsset", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="Section")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Section : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Section object.
        /// </summary>
        /// <param name="sectionId">Initial value of the SectionId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        public static Section CreateSection(global::System.Int32 sectionId, global::System.String name, global::System.DateTime createdAt)
        {
            Section section = new Section();
            section.SectionId = sectionId;
            section.Name = name;
            section.CreatedAt = createdAt;
            return section;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SectionId
        {
            get
            {
                return _SectionId;
            }
            set
            {
                if (_SectionId != value)
                {
                    OnSectionIdChanging(value);
                    ReportPropertyChanging("SectionId");
                    _SectionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SectionId");
                    OnSectionIdChanged();
                }
            }
        }
        private global::System.Int32 _SectionId;
        partial void OnSectionIdChanging(global::System.Int32 value);
        partial void OnSectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__Article__Section__5EBF139D", "Article")]
        public EntityCollection<Article> Article
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Article>("ElijaModel.FK__Article__Section__5EBF139D", "Article");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Article>("ElijaModel.FK__Article__Section__5EBF139D", "Article", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="token">Initial value of the Token property.</param>
        public static User CreateUser(global::System.Int64 userId, global::System.Guid token)
        {
            User user = new User();
            user.UserId = userId;
            user.Token = token;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> FacebookId
        {
            get
            {
                return _FacebookId;
            }
            set
            {
                OnFacebookIdChanging(value);
                ReportPropertyChanging("FacebookId");
                _FacebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacebookId");
                OnFacebookIdChanged();
            }
        }
        private Nullable<global::System.Int64> _FacebookId;
        partial void OnFacebookIdChanging(Nullable<global::System.Int64> value);
        partial void OnFacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookLink
        {
            get
            {
                return _FacebookLink;
            }
            set
            {
                OnFacebookLinkChanging(value);
                ReportPropertyChanging("FacebookLink");
                _FacebookLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookLink");
                OnFacebookLinkChanged();
            }
        }
        private global::System.String _FacebookLink;
        partial void OnFacebookLinkChanging(global::System.String value);
        partial void OnFacebookLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneHome
        {
            get
            {
                return _TelephoneHome;
            }
            set
            {
                OnTelephoneHomeChanging(value);
                ReportPropertyChanging("TelephoneHome");
                _TelephoneHome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneHome");
                OnTelephoneHomeChanged();
            }
        }
        private global::System.String _TelephoneHome;
        partial void OnTelephoneHomeChanging(global::System.String value);
        partial void OnTelephoneHomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneOffice
        {
            get
            {
                return _TelephoneOffice;
            }
            set
            {
                OnTelephoneOfficeChanging(value);
                ReportPropertyChanging("TelephoneOffice");
                _TelephoneOffice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneOffice");
                OnTelephoneOfficeChanged();
            }
        }
        private global::System.String _TelephoneOffice;
        partial void OnTelephoneOfficeChanging(global::System.String value);
        partial void OnTelephoneOfficeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneMobile
        {
            get
            {
                return _TelephoneMobile;
            }
            set
            {
                OnTelephoneMobileChanging(value);
                ReportPropertyChanging("TelephoneMobile");
                _TelephoneMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneMobile");
                OnTelephoneMobileChanged();
            }
        }
        private global::System.String _TelephoneMobile;
        partial void OnTelephoneMobileChanging(global::System.String value);
        partial void OnTelephoneMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDate;
        partial void OnRegistrationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.Guid _Token;
        partial void OnTokenChanging(global::System.Guid value);
        partial void OnTokenChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__UserDevic__UserI__49C3F6B7", "UserDevice")]
        public EntityCollection<UserDevice> UserDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserDevice>("ElijaModel.FK__UserDevic__UserI__49C3F6B7", "UserDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserDevice>("ElijaModel.FK__UserDevic__UserI__49C3F6B7", "UserDevice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="UserDevice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserDevice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserDevice object.
        /// </summary>
        /// <param name="userDeviceId">Initial value of the UserDeviceId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="deviceId">Initial value of the DeviceId property.</param>
        /// <param name="createdAt">Initial value of the CreatedAt property.</param>
        /// <param name="lastActivityDate">Initial value of the LastActivityDate property.</param>
        public static UserDevice CreateUserDevice(global::System.Int64 userDeviceId, global::System.Int64 userId, global::System.Int64 deviceId, global::System.DateTime createdAt, global::System.DateTime lastActivityDate)
        {
            UserDevice userDevice = new UserDevice();
            userDevice.UserDeviceId = userDeviceId;
            userDevice.UserId = userId;
            userDevice.DeviceId = deviceId;
            userDevice.CreatedAt = createdAt;
            userDevice.LastActivityDate = lastActivityDate;
            return userDevice;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserDeviceId
        {
            get
            {
                return _UserDeviceId;
            }
            set
            {
                if (_UserDeviceId != value)
                {
                    OnUserDeviceIdChanging(value);
                    ReportPropertyChanging("UserDeviceId");
                    _UserDeviceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserDeviceId");
                    OnUserDeviceIdChanged();
                }
            }
        }
        private global::System.Int64 _UserDeviceId;
        partial void OnUserDeviceIdChanging(global::System.Int64 value);
        partial void OnUserDeviceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int64 _UserId;
        partial void OnUserIdChanging(global::System.Int64 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DeviceId
        {
            get
            {
                return _DeviceId;
            }
            set
            {
                OnDeviceIdChanging(value);
                ReportPropertyChanging("DeviceId");
                _DeviceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviceId");
                OnDeviceIdChanged();
            }
        }
        private global::System.Int64 _DeviceId;
        partial void OnDeviceIdChanging(global::System.Int64 value);
        partial void OnDeviceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__UserDevic__Devic__4AB81AF0", "Device")]
        public Device Device
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("ElijaModel.FK__UserDevic__Devic__4AB81AF0", "Device").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("ElijaModel.FK__UserDevic__Devic__4AB81AF0", "Device").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Device> DeviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("ElijaModel.FK__UserDevic__Devic__4AB81AF0", "Device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Device>("ElijaModel.FK__UserDevic__Devic__4AB81AF0", "Device", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__UserDevic__UserI__49C3F6B7", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ElijaModel.FK__UserDevic__UserI__49C3F6B7", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ElijaModel.FK__UserDevic__UserI__49C3F6B7", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("ElijaModel.FK__UserDevic__UserI__49C3F6B7", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("ElijaModel.FK__UserDevic__UserI__49C3F6B7", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ElijaModel", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="videoId">Initial value of the VideoId property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static Video CreateVideo(global::System.Int32 videoId, global::System.String url)
        {
            Video video = new Video();
            video.VideoId = videoId;
            video.Url = url;
            return video;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VideoId
        {
            get
            {
                return _VideoId;
            }
            set
            {
                if (_VideoId != value)
                {
                    OnVideoIdChanging(value);
                    ReportPropertyChanging("VideoId");
                    _VideoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VideoId");
                    OnVideoIdChanged();
                }
            }
        }
        private global::System.Int32 _VideoId;
        partial void OnVideoIdChanging(global::System.Int32 value);
        partial void OnVideoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ElijaModel", "FK__ArticleAs__Video__6B24EA82", "ArticleAsset")]
        public EntityCollection<ArticleAsset> ArticleAsset
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ArticleAsset>("ElijaModel.FK__ArticleAs__Video__6B24EA82", "ArticleAsset");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ArticleAsset>("ElijaModel.FK__ArticleAs__Video__6B24EA82", "ArticleAsset", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
