//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freakybite.ElijaWebServices.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserDevice = new HashSet<UserDevice>();
        }
    
        public long UserId { get; set; }
        public Nullable<long> FacebookId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public string FacebookLink { get; set; }
        public string TelephoneHome { get; set; }
        public string TelephoneOffice { get; set; }
        public string TelephoneMobile { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public System.Guid Token { get; set; }
    
        public virtual ICollection<UserDevice> UserDevice { get; set; }
    }
}
